/**
 * paintings.js — Gallery data source
 * Generated by editor.html on 2026-08-04.
 */

const PAINTINGS = [
  {
    id: "forest",
    seoCategory: "Fantasy Landscape Illustration",
    title: "Forest",
    year: "2026",
    medium: "Digital painting",
    desc: "A sprawling ancient forest bathed in light.",
    thumbnail: "assets/illustrations/forest_bloomborrow_final.webp",
    stages: [
      { src: "assets/illustrations/forest_bloomborrow_final.webp" },
      { src: "assets/illustrations/forest_bloomburrow_card_frame.jpg" },
      { src: "assets/illustrations/forest_drawing.webp" },
      { src: "assets/illustrations/forest_thumbs.webp" },
    ],
  },
  {
    id: "plains",
    seoCategory: "Environment Landscape Illustration",
    title: "Plains",
    year: "2026",
    medium: "Digital painting",
    desc: "Wide-open grassland at golden hour.",
    thumbnail: "assets/illustrations/plains_final.webp",
  },
  {
    id: "umbral_rift",
    seoCategory: "Fantasy Environment Art",
    title: "Umbral Rift",
    year: "2026",
    medium: "Digital painting",
    desc: "A monumental beast-mouth cavern entrance.",
    thumbnail: "assets/illustrations/umbral_rift_final.webp",
  },
  {
    id: "ash_monolith",
    seoCategory: "Landscape Illustration",
    title: "Ash Monolith",
    year: "2025",
    medium: "Digital painting",
    desc: "A solitary ancient monolith rises from an ash-covered plain.",
    thumbnail: "assets/illustrations/ash_monolith_final.webp",
  },
  {
    id: "mana_breach",
    seoCategory: "Fantasy Landscape Art",
    title: "Mana Breach",
    year: "2025",
    medium: "Digital painting",
    desc: "An arcane rupture tears through a ruined landscape.",
    thumbnail: "assets/illustrations/mana_breach_final.webp",
  },
  {
    id: "whispers_from_the_mireglass",
    seoCategory: "Landscape Illustration",
    title: "Whispers from the Mireglass",
    year: "2025",
    medium: "Digital painting",
    desc: "A reflective swamp with ghostly apparitions.",
    thumbnail: "assets/illustrations/whispers_from_the_mireglass_final.webp",
  },
  {
    id: "heartroot_vault",
    seoCategory: "Environment Illustration",
    title: "Heartroot Vault",
    year: "2025",
    medium: "Digital painting",
    desc: "A vast underground root network forms a cathedral-like natural vault.",
    thumbnail: "assets/illustrations/heartroot_vault_final.webp",
  },
  {
    id: "paradox_hollow",
    seoCategory: "Landscape Illustration",
    title: "Paradox Hollow",
    year: "2025",
    medium: "Digital painting",
    desc: "A spatially distorted desert where geometry defies logic.",
    thumbnail: "assets/illustrations/paradox_hollow_final.webp",
  },
  {
    id: "the_artifact_vault",
    seoCategory: "Environment Illustration",
    title: "The Artifact Vault",
    year: "2025",
    medium: "Digital painting",
    desc: "An old catacomb guarded by creepy spiders.",
    thumbnail: "assets/illustrations/the_artifact_vault_final.webp",
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PAINTINGS;
}
