/**
 * paintings.js — Gallery data source
 * Generated by editor.html on 2026-10-07.
 * images[0] is the cover; every image is shown, in order, in the lightbox.
 */

const PAINTINGS = [
  {
    id: "spire_at_dusk",
    seoCategory: "Environment Illustration",
    title: "Spire at Dusk",
    year: "",
    medium: "Digital painting",
    desc: "A lone crystal spire crowned with blue flame rises from a desert plain at sunset.",
    images: [
      { src: "assets/illustrations/spire_at_dusk_final.webp", caption: "Final" },
      { src: "assets/illustrations/spire_at_dusk_line_drawing.webp", caption: "Line drawing" },
    ],
  },
  {
    id: "bone_cavern",
    seoCategory: "Fantasy Environment Art",
    title: "Bone Cavern",
    year: "2026",
    medium: "Digital painting",
    desc: "A cavern mouth framed by enormous bone tusks.",
    images: [
      { src: "assets/illustrations/bone_cavern_final.webp", caption: "Final" },
      { src: "assets/illustrations/bone_cavern_line_drawing.webp", caption: "Line drawing" },
      { src: "assets/illustrations/bone_cavern_thumbnails.webp", caption: "Thumbnails" },
    ],
  },
  {
    id: "vine_canyon",
    seoCategory: "Fantasy Landscape Illustration",
    title: "Vine Canyon",
    year: "2026",
    medium: "Digital painting",
    desc: "A stream winds through a canyon of giant twisting vines and weathered stone.",
    images: [
      { src: "assets/illustrations/vine_canyon_final.webp", caption: "Final" },
      { src: "assets/illustrations/vine_canyon_line_drawing.webp", caption: "Line drawing" },
      { src: "assets/illustrations/vine_canyon_thumbnails.webp", caption: "Thumbnails" },
    ],
  },
  {
    id: "sanctuary_gate",
    seoCategory: "Fantasy Landscape Art",
    title: "Sanctuary Gate",
    year: "2025",
    medium: "Digital painting",
    desc: "A vine-covered stone sanctuary crowned by a great ring, with a wheel-like gate at its foot.",
    images: [
      { src: "assets/illustrations/sanctuary_gate_final.webp", caption: "Final" },
      { src: "assets/illustrations/sanctuary_gate_line_drawing.webp", caption: "Line drawing" },
      { src: "assets/illustrations/sanctuary_gate_thumbnails.webp", caption: "Thumbnails" },
    ],
  },
  {
    id: "stone_arch",
    seoCategory: "Environment Landscape Illustration",
    title: "Stone Arch",
    year: "",
    medium: "Digital painting",
    desc: "A desert path winds beneath a natural stone arch filled with light.",
    images: [
      { src: "assets/illustrations/stone_arch_final.webp", caption: "Final" },
      { src: "assets/illustrations/stone_arch_line_drawing.webp", caption: "Line drawing" },
      { src: "assets/illustrations/stone_arch_thumbnails.webp", caption: "Thumbnails" },
    ],
  },
  {
    id: "sunset_tower",
    seoCategory: "Environment Landscape Illustration",
    title: "Sunset Tower",
    year: "2026",
    medium: "Digital painting",
    desc: "A lone stone tower stands in golden grassland beneath a sunset sky.",
    images: [
      { src: "assets/illustrations/sunset_tower_final.webp", caption: "Final" },
      { src: "assets/illustrations/sunset_tower_line_drawing.webp", caption: "Line drawing" },
      { src: "assets/illustrations/sunset_tower_thumbnails.webp", caption: "Thumbnails" },
    ],
  },
  {
    id: "ancient_grove",
    seoCategory: "Environment Illustration",
    title: "Ancient Grove",
    year: "2025",
    medium: "Digital painting",
    desc: "Massive ancient roots and trunks rise above a glowing green pool.",
    images: [
      { src: "assets/illustrations/ancient_grove_final.webp" },
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PAINTINGS;
}
