/**
 * paintings.js — Gallery data source
 * Generated by editor.html on 2026-08-05.
 * images[0] is the cover; every image is shown, in order, in the lightbox.
 */

const PAINTINGS = [
  {
    id: "forest",
    seoCategory: "Fantasy Landscape Illustration",
    title: "Forest",
    year: "2026",
    medium: "Digital painting",
    desc: "A sprawling ancient forest bathed in light.",
    images: [
      { src: "assets/illustrations/forest_bloomborrow_final.webp" },
      { src: "assets/illustrations/forest_bloomburrow_card_frame.jpg" },
      { src: "assets/illustrations/forest_bloomborrow_drawing.jpg" },
      { src: "assets/illustrations/forest_bloomborrow_thumbs.jpg" },
    ],
  },
  {
    id: "plains",
    seoCategory: "Environment Landscape Illustration",
    title: "Plains",
    year: "2026",
    medium: "Digital painting",
    desc: "Wide-open grassland at golden hour.",
    images: [
      { src: "assets/illustrations/plains_final.webp" },
    ],
  },
  {
    id: "umbral_rift",
    seoCategory: "Fantasy Environment Art",
    title: "Umbral Rift",
    year: "2026",
    medium: "Digital painting",
    desc: "A monumental beast-mouth cavern entrance.",
    images: [
      { src: "assets/illustrations/umbral_rift_final.webp" },
    ],
  },
  {
    id: "mana_breach",
    seoCategory: "Fantasy Landscape Art",
    title: "Mana Breach",
    year: "2025",
    medium: "Digital painting",
    desc: "An arcane rupture tears through a ruined landscape.",
    images: [
      { src: "assets/illustrations/mana_breach_final.webp" },
    ],
  },
  {
    id: "heartroot_vault",
    seoCategory: "Environment Illustration",
    title: "Heartroot Vault",
    year: "2025",
    medium: "Digital painting",
    desc: "A vast underground root network forms a cathedral-like natural vault.",
    images: [
      { src: "assets/illustrations/heartroot_vault_final.webp" },
    ],
  },
  {
    id: "the_artifact_vault",
    seoCategory: "Environment Illustration",
    title: "The Artifact Vault",
    year: "2025",
    medium: "Digital painting",
    desc: "An old catacomb guarded by creepy spiders.",
    images: [
      { src: "assets/illustrations/the_artifact_vault_final.webp" },
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PAINTINGS;
}
